### ISSUE TITLE
Optional Dependencies

### ISSUE THREAD

**Issue by Eeems** [toltec-dev/build#5]
We should implement something similar to [optdepends in PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD#optdepends). On install we can list out all the optional dependencies, their usage description, and indicate if they are already installed or not.

**Comment by matteodelabre** [comment]
In a similar fashion to Debian, Opkg supports two concepts that are close to Arch’s `optdepends`: `Suggests` and `Recommends`.

* `Recommends` is a weaker version of `Depends`: it will automatically install the listed dependencies whenever possible, otherwise it will simply print `A: unsatisfied recommendation for B` and continue on.

* `Suggests` (closest to `optdepends`) is a weaker version of `Recommends`: it will not automatically install any package listed, but will print `package A suggests installing B` upon installation.

From [Debian docs](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps):

> `Recommends`
>
>    This declares a strong, but not absolute, dependency.
>
>    The Recommends field should list packages that would be found together with this one in all but unusual installations.
>
> `Suggests`
>
>    This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.

**Comment by Eeems** [comment]
It sounds like we should implement `Suggests` support.

**Comment by matteodelabre** [comment]
I think we could map `optdepends=()` to `Suggests` and also support `Recommends` in a separate `recommends=()` field, in case someone needs this feature.

Do you think one of the two could be useful for the Oxide set of packages in Toltec?

**Comment by Eeems** [comment]
I think optdepends would be useful for Oxide as I add more built in, but optional applications. I don't really see a use for recommends yet.

**Comment by matteodelabre** [comment]
Fixed in 90e200bad2d3c4ec01694699513d03a3e097fef5 with new fields `optdepends=()` and `recommends=()`.
